// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3yey9gjAOd2rHrHWeIB-yHnqEAs7b58Y',
    appId: '1:388681426135:android:dd4cd7f67bf0a6cf14bc92',
    messagingSenderId: '388681426135',
    projectId: 'alexu-a9210',
    storageBucket: 'alexu-a9210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6G_K3kbpl_mKKb05WCANpQJAXS-QpYfA',
    appId: '1:388681426135:ios:6492ddbc23491ee614bc92',
    messagingSenderId: '388681426135',
    projectId: 'alexu-a9210',
    storageBucket: 'alexu-a9210.appspot.com',
    androidClientId: '388681426135-2v3a9ifh3ffqfhekqsgs4phva4q6gfl7.apps.googleusercontent.com',
    iosClientId: '388681426135-jhf7p9l1vird6bdnrj8l1jnofqv6usfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexuadmin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdLZU07nid-SKuEQlMiVKQJm7RraHzdA',
    appId: '1:388681426135:web:d2f7f63b19b640e414bc92',
    messagingSenderId: '388681426135',
    projectId: 'alexu-a9210',
    authDomain: 'alexu-a9210.firebaseapp.com',
    storageBucket: 'alexu-a9210.appspot.com',
    measurementId: 'G-QWBD3NE23K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6G_K3kbpl_mKKb05WCANpQJAXS-QpYfA',
    appId: '1:388681426135:ios:6492ddbc23491ee614bc92',
    messagingSenderId: '388681426135',
    projectId: 'alexu-a9210',
    storageBucket: 'alexu-a9210.appspot.com',
    androidClientId: '388681426135-2v3a9ifh3ffqfhekqsgs4phva4q6gfl7.apps.googleusercontent.com',
    iosClientId: '388681426135-jhf7p9l1vird6bdnrj8l1jnofqv6usfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.alexuadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkdLZU07nid-SKuEQlMiVKQJm7RraHzdA',
    appId: '1:388681426135:web:a1e4c797a7062de914bc92',
    messagingSenderId: '388681426135',
    projectId: 'alexu-a9210',
    authDomain: 'alexu-a9210.firebaseapp.com',
    storageBucket: 'alexu-a9210.appspot.com',
    measurementId: 'G-WJM05WV117',
  );

}